//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToneHouseMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Diet
    {
        public int DietID { get; set; }
        public int TypeID { get; set; }
        public string DishName { get; set; }
        public string DishDes { get; set; }
        public string DishTime { get; set; }
        public string ImagePath { get; set; }
    
        public virtual tb_Type tb_Type { get; set; }
    }
}
