//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToneHouseMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PlanOpted
    {
        public int PlanOptedId { get; set; }
        public int UserId { get; set; }
        public int ExerciseId { get; set; }
        public Nullable<double> Time { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<double> Calories { get; set; }
        public Nullable<int> PaymentId { get; set; }
    
        public virtual tb_Payment tb_Payment { get; set; }
        public virtual tb_SignUp tb_SignUp { get; set; }
    }
}
